# Generated by Django 2.2.3 on 2019-08-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
